# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/sample/ping
Accept: application/json

###
POST http://127.0.0.1:8000/sample/ping
Accept: application/json

{
    "name": "new test123"
}

###
GET http://127.0.0.1:8000/sample/ping/all
Accept: application/json

###
POST http://localhost:8000/courses/
Accept: application/json
Content-Type: application/json

{
  "course_code":  "CS102",
  "name":         "컴퓨터 과학 입문",
  "description":  "컴퓨터 공학의 기초 원리를 배우는 강의입니다.",
  "professor_id": 1,
  "location":     "공학관 301호",
  "days_of_week": "Mon,Wed,Fri",
  "start_time":   "09:00:00",
  "end_time":     "10:15:00",
  "department_id":2,
  "credits":      3,
  "capacity":     40,
  "prerequisite":"없음",
  "semester":     "2023-1"
}

###
GET http://127.0.0.1:8000/courses/
Accept: application/json

###
GET http://127.0.0.1:8000/courses/100
Accept: application/json
